controllers/SiteController.php
<?php

namespace restapi\controllers;

use yii\web\Controller;

/**
 * Site front controller
 * @package restapi\controllers
 */
class SiteController extends Controller
{
    /**
     * Default site action
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Example page contains forms for sending requests to REST API
     * @return string
     */
    public function actionExample()
    {
        return $this->render('example');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use restapi\assets\AppAsset;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Главная', 'url' => ['/site/index']],
        ['label' => 'Примеры', 'url' => ['/site/example']],
    ];
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'REST API';
?>
<div class="site-index">
    <p>Реализовать простое REST API с одним единственным методом, который загружает изображения.</p>

    <p>Требования:</p>
    <ul>
        <li>Возможность загружать несколько файлов.</li>
        <li>Возможность принимать multipart/form-data запросы.</li>
        <li>Возможность принимать JSON запросы с BASE64 закодированными изображениями.</li>
        <li>Возможность загружать изображения по заданному URL (изображение размещено где-то в интернете).</li>
        <li>Создание квадратного превью изображения размером 100px на 100px.</li>
    </ul>

    <p>На странице <?= \yii\bootstrap\Html::a('примеров', ['example']) ?> можно отправить типовые запросы к API.</p>
</div>